<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16" started-at="2019-03-01T06:22:02Z" finished-at="2019-03-01T06:22:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16" started-at="2019-03-01T06:22:02Z" finished-at="2019-03-01T06:22:02Z">
      <class name="k0301.k0301.k0310Test">
        <test-method status="SKIP" signature="ma(java.lang.String, java.lang.String)[pri:0, instance:k0301.k0301.k0310Test@4415d52e]" name="ma" duration-ms="0" started-at="2019-03-01T14:22:02Z" data-provider="providUser" finished-at="2019-03-01T14:22:02Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public static void k0301.k0301.k0310Test.ma(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : providUser]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public static void k0301.k0301.k0310Test.ma(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : providUser
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ma -->
      </class> <!-- k0301.k0301.k0310Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
